[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.networks.forked-sepolia]
type = "forked"
url = "https://eth-sepolia.g.alchemy.com/v2/2L8rIM6Q5Z4tyBCHsPRgC22Fx-JVA4T0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
