[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.networks.forked-sepolia]
type = "forked"

[profile.ethereum]
network = "sepolia"
account = "0xb7B943fFbA78e33589971e630AD6EB544252D88C"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
